services:
  mariadb:
    image: mariadb:lts-ubi
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  init_service:
    build:
      context: .
      dockerfile: backend/init_service/Dockerfile
    container_name: init_service
    restart: no
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true


# openmeteo_client:
#   build:
#     context: ./openmeteo_client
#     dockerfile: Dockerfile
#   container_name: openmeteo_client
#   restart: on-failure
#   environment:
#     MYSQL_HOST: mariadb
#     MYSQL_PORT: 3306
#     MYSQL_DATABASE: weatherdb
#     MYSQL_USER: myuser
#     MYSQL_PASSWORD: mypassword
#   depends_on:
#     mariadb:
#       condition: service_healthy
#     db_init:
#       condition: service_completed_successfully

# api:
#   build:
#     context: ./api
#     dockerfile: Dockerfile
#   container_name: api
#   restart: on-failure
#   environment:
#     MYSQL_HOST: mariadb
#     MYSQL_PORT: 3306
#     MYSQL_DATABASE: weatherdb
#     MYSQL_USER: myuser
#     MYSQL_PASSWORD: mypassword
#   ports:
#     - "8001:8001"
#   depends_on:
#     mariadb:
#       condition: service_healthy


volumes:
  mariadb_data:
