services:
  mariadb:
    image: mariadb:lts-ubi
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  openmeteo_client:
    build:
      context: ./openmeteo_client
      dockerfile: Dockerfile
    container_name: openmeteo_client
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
