services:
  database:
    image: postgres:16-alpine
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pw
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d weatherdb"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  build-service:
    build:
      context: .
      dockerfile: build_service/Dockerfile
      target: weather-build-service
    container_name: weather-build-service
    image: weather-build-service:${BUILD_SERVICE_VERSION}

  bootstrap-service:
    build:
      context: .
      dockerfile: bootstrap_service/Dockerfile
    container_name: weather-bootstrap-service
    image: weather-bootstrap-service:${BOOTSTRAP_SERVICE_VERSION}
    restart: no
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: weatherdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pw
      CONFIG_FILE: dev_config.json
    depends_on:
      build-service:
        condition: service_completed_successfully
      database:
        condition: service_healthy
        restart: true

  maintenance-service:
    build:
      context: .
      dockerfile: maintenance_service/Dockerfile
    container_name: weather-maintenance-service
    image: weather-maintenance-service:${MAINTENANCE_SERVICE_VERSION}
    restart: no
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: weatherdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pw
      CONFIG_FILE: dev_config.json
    depends_on:
      build-service:
        condition: service_completed_successfully
      database:
        condition: service_healthy
        restart: true
      bootstrap-service:
        condition: service_completed_successfully

volumes:
  data:
