name: Python Setup
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./openmeteo_client/requirements.txt
      shell: bash