name: CD Pipeline - Build and Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging
      services:
        description: 'Services to build (comma-separated, or "all" for all services)'
        required: false
        default: 'all'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cloud-native-projekt/weather-service

jobs:
  build-base:
    name: Build Base Service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      build-service-image: ${{ steps.image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for build_service
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/build_service
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push build_service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build_service/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set output
        id: image
        run: echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/build_service:${{ github.sha }}" >> $GITHUB_OUTPUT

  build-services:
    name: Build Services
    runs-on: ubuntu-latest
    needs: build-base
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - name: bootstrap_service
            dockerfile: bootstrap_service/Dockerfile
          - name: daily_maintenance_service
            dockerfile: daily_maintenance_service/Dockerfile
          - name: forecast_service
            dockerfile: forecast_service/Dockerfile
          - name: forecast_build_service
            dockerfile: forecast_build_service/Dockerfile
          - name: weekly_maintenance_service
            dockerfile: weekly_maintenance_service/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if service should be built
        id: should_build
        run: |
          SERVICES_INPUT="${{ github.event.inputs.services }}"
          SERVICE_NAME="${{ matrix.service.name }}"
          
          if [ "$SERVICES_INPUT" = "all" ] || [ -z "$SERVICES_INPUT" ]; then
            echo "build=true" >> $GITHUB_OUTPUT
          elif echo "$SERVICES_INPUT" | grep -q "$SERVICE_NAME"; then
            echo "build=true" >> $GITHUB_OUTPUT
          else
            echo "build=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.should_build.outputs.build == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: steps.should_build.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        if: steps.should_build.outputs.build == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push ${{ matrix.service.name }}
        if: steps.should_build.outputs.build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          build-args: BUILD_SERVICE_IMAGE=${{ needs.build-base.outputs.build-service-image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-base, build-services]
    if: always()
    steps:
      - name: Build Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Services**: ${{ github.event.inputs.services }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit SHA**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Images have been pushed to GHCR and are ready for deployment." >> $GITHUB_STEP_SUMMARY
