name: CI/CD

on:
  push:
    branches:
      - 'feature/**'
  pull_request:

permissions:
  contents: read
  packages: write
  security-events: write
  actions: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code Linting
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./openmeteo_client/requirements.txt

      - name: Install linters
        run: pip install flake8 black mypy

      - name: Run flake8
        run: flake8 . --max-line-length=120 --extend-ignore=E203,W503 --exclude=build,dist,.venv

      - name: Run black
        run: black . --line-length=120 --target-version=py313

      - name: Run mypy
        run: mypy . --install-types --non-interactive